import Head from "next/head";
import Image from "next/image";
import BmiCalculatorSection from "../components/Home/BmiCalculatorSection";
import DownloadAppSection from "../components/Home/DownloadAppSection";
import FootballPlayerSection from "../components/Home/FootballPlayerSection";
import ThingsSection from "../components/Home/ThingsSection";
import ThingsSection2 from "../components/Home/ThingsSection2";
import ThingsSection3 from "../components/Home/ThingsSection3";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import BannerSection from "../components/Home/BannerSection";
import LookingForSection from "../components/Home/LookingForSection";
import BlogSection from "../components/Home/BlogSection";
import axios from "axios";
import backendHost from "../utils/backendHost";
import idSlugConverter from "../utils/idSlugConverter";
import { useEffect } from "react";

export default function Home({categories}) {
  
  
  return (
    <div className="">
      <Head>
        <title>Fitz Cornerz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-small.png" />
      </Head>
        <BannerSection />
        <LookingForSection data={categories} />
        <BlogSection />
        <BmiCalculatorSection />
        <ThingsSection />
        <FootballPlayerSection />
        <ThingsSection2 />
        <ThingsSection3 />
        <DownloadAppSection />
    </div>
  );
}

export async function getStaticProps() {
  const props = {
    categories: [],
  };
  try {
    //To obtain slug from category
    const categories = await axios.get(`${backendHost}/category`);
    props.categories = [...categories.data];
    
    return {props};
  } catch (err) {
    console.log(err);
    return {props};
  }
}