import Head from "next/head";
import BmiCalculatorSection from "../components/Home/BmiCalculatorSection";
import DownloadAppSection from "../components/Home/DownloadAppSection";
import FootballPlayerSection from "../components/Home/FootballPlayerSection";
import ThingsSection from "../components/Home/ThingsSection";
import ThingsSection2 from "../components/Home/ThingsSection2";
import ThingsSection3 from "../components/Home/ThingsSection3";
import Layout from "../components/Layout";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import BannerSection from "../components/Home/BannerSection";
import LookingForSection from "../components/Home/LookingForSection";
import BlogSection from "../components/Home/BlogSection";
import axios from "axios";
import backendHost from "../utils/backendHost";

export default function Home({ dir, categories, blogs }) {
  return (
    <Layout categories={categories} dir={dir}>
      <Head>
        <title>Fitz Cornerz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-small.png" />
      </Head>

      <BannerSection />
      <div className="container mx-auto px-3 md:max-w-[90%] lg:max-w-[80%]">
        <LookingForSection data={categories} />
        <BlogSection data={blogs} />
        <BmiCalculatorSection />
      </div>
        <ThingsSection />
        <FootballPlayerSection />
        <ThingsSection2 />
        <ThingsSection3 />
        <DownloadAppSection />
    </Layout>
  );
}

export async function getStaticProps(context) {
  const props = {
    categories: [],
    blogs: [],
  };
  try {
    const { locale } = context;
    const categories = await axios.get(`${backendHost}/category`, {
      headers: {
        "Accept-Language": locale,
      },
    });
    //Passing categories to be used in header and footer
    props.categories = [...categories.data];
    //To use blog in blogsection
    const blogs = await axios.get(`${backendHost}/blog`, {
      headers: {
        "Accept-Language": locale,
      },
    });
    props.blogs = [...blogs.data];

    return { props, revalidate:10 };
  } catch (err) {
    console.log(err);
    return { props };
  }
}
